# Generated by Django 5.0.6 on 2024-07-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('high_school_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dob', models.DateField()),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.combination')),
            ],
        ),
    ]
