# Generated by Django 5.0.6 on 2024-07-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_studentapplication_high_school_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='stName',
            new_name='stname',
        ),
    ]
