# Generated by Django 5.0.6 on 2024-07-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_stname_studentapplication_stname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='stname',
            new_name='stName',
        ),
    ]
