# Generated by Django 5.0.6 on 2024-07-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_user_delete_studentapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='combination',
        ),
        migrations.AddField(
            model_name='combination',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='combination',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
